apiVersion: v1
kind: Service
metadata:
  name: products-db
  labels:
    app: wiredbrain
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    component: products-db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
  labels:
    app: wiredbrain
spec:
  selector:
    matchLabels:
        app: wiredbrain
        component: products-db
  template:
    metadata:
      labels: 
        app: wiredbrain
        component: products-db
    spec:
      containers:
        - name: app
          image: wiredbrain/products-db:22.03