apiVersion: v1
kind: Service
metadata:
  name: stock-api
  labels:
    app: wiredbrain
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    component: stock-api
  type: ClusterIP
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
  labels:
    app: wiredbrain
spec:
  selector:
    matchLabels:
        app: wiredbrain
        component: stock-api
  template:
    metadata:
      labels: 
        app: wiredbrain
        component: stock-api
    spec:
      containers:
        - name: app
          image: wiredbrain/stock-api:22.03