apiVersion: v1
kind: Service
metadata:
  name: stock-api-lb
  labels:
    app: wiredbrain
spec:
  ports:
    - port: 8090
      targetPort: 8080
  selector:
    component: stock-api
  type: LoadBalancer
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-api-config-db
  labels: 
    app: wiredbrain
    component: stock-api
data:
  POSTGRES_CONNECTION_STRING: "host=products-db-cl port=5432 user=postgres password=wired dbname=postgres sslmode=disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
  labels:
    app: wiredbrain
spec:
  selector:
    matchLabels:
        app: wiredbrain
        component: stock-api
  template:
    metadata:
      labels: 
        app: wiredbrain
        component: stock-api
    spec:
      containers:
        - name: app
          image: wiredbrain/stock-api:22.05
          env:
            - name: CACHE_EXPIRY_SECONDS
              value: '5'
          envFrom:
            - configMapRef:
                name: stock-api-config-db
          volumeMounts:
            - name: cache
              mountPath: "/cache"
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: cache
          emptyDir: {}
            