apiVersion: v1
kind: Service
metadata:
  name: products-api-cl
  labels:
    app: wiredbrain
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: products-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  labels:
    app: wiredbrain
spec:
  selector:
    matchLabels:
        app: wiredbrain
        component: products-api
  template:
    metadata:
      labels:
        app: wiredbrain
        component: products-api
    spec:
      containers:
        - name: app
          image: wiredbrain/products-api:22.03
          volumeMounts:
            - name: db-properties
              mountPath: "/app/config/db"
              readOnly: true
      volumes:
        - name: db-properties
          configMap:
            name: products-api-config-db

