apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config-api
  labels: 
    app: wiredbrain
    component: web
data:
  api.json: |-
    {
      "ProductsApi": {
        "Url": "http://products-api-cl/products"
      },
      "StockApi": {
        "Url": "http://stock-api-cl/stock"
      },
      "Environment": "PRE-PROD"
    }