apiVersion: batch/v1
kind: Job
metadata:
  name: test-user
  namespace: users 
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: user-cert-generator
      containers:
        - name: generator
          image: sixeyed/user-cert-generator 
          env:
            - name: USER_NAME
              value: rishi
            - name: GROUP
              value: tester
            - name: PRINT_CERTS
              value: 'true'