apiVersion: v1
kind: PersistentVolume
metadata:
  name: products-db-pv
  labels: 
    app: wiredbrain
    component: products-db
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /volumes/products-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values: ['docker-desktop']
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-db-pvc-manual
  labels: 
    app: wiredbrain
    component: products-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  volumeName: products-db-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
  labels:
    app: wiredbrain
spec:
  selector:
    matchLabels:
        app: wiredbrain
        component: products-db
  template:
    metadata:
      labels: 
        app: wiredbrain
        component: products-db
        storage: hostpath
    spec:
      containers:
        - name: app
          image: wiredbrain/products-db:22.05
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data 
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: products-db-pvc-manual